version: "3.7"

services:

    back:
        build: jdr-back
        ports:
            - 8080:8080
        environment: 
            - SERVER_PORT=8080
            - MONGO_HOST=mongo
            - MONGO_PORT=27017
            - MONGO_DB=jdr
        depends_on:
            - mongo

    front:
        build: JDR-Front
        ports:
            - 80:80
        depends_on:
            - jdr-back  
        
        
    mongo:
        image: mongo
        restart: always
        volumes: 
            - ./data/db:/data/db    
        ports:
            - 27017:27017

