version: "3.3"

services:
    mongo:
        image: mongo
        ports:
            - 27017:27017
    back:
        build: jdr-back
        ports:
            - 8080:8080
        environment: 
            - SERVER_PORT=8080
            - MONGO_HOST=mongo
        depends_on:
            - mongo
    front:
        build: JDR-Front
        ports:
            - 80:80
